# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            phocks
tagline:          'guarding the henhouse'
description:      'a blog.'
url:              http://phocks.github.io/
baseurl:          '/'
paginate:         5

author:
  name:           'Joshua Byrd'
  url:            https://twitter.com/phocks

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/phocks/phocks.github.io
