# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        none

# Setup
title:            phocks
tagline:          'observations on life, the universe, and nothing'
description:      'Some kind of blog written by Joshua Byrd.'
url:              http://phocks.github.io/
baseurl:          '/'
paginate:         5
timezone:         Australia/Brisbane
encoding:         utf-8

author:
  name:           'Joshua Byrd'
  url:            https://twitter.com/phocks

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/phocks/phocks.github.io

gems:             ['jekyll-paginate']
