# Site settings
title: "phocks"
description: "a dev blog or something"
tagline: "a dev blog or something"
# baseurl: "/textlog" # required if used under gh-pages branch, else (under master branch) just leave empty/blank
url: ""
author:
  name:           'Joshua Byrd'
  url:            https://twitter.com/phocks

# Build settings
kramdown:
  input: GFM
permalink: none

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname: 

plugins:
  - jekyll-sitemap

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]
