# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        none

# Setup
title:            phocks
tagline:          'guarding the henhouse'
description:      'A simple blog, built on Jekyll, about the simple things in the daily life of Joshua Byrd.'
url:              http://phocks.github.io/
baseurl:          '/'
paginate:         5

author:
  name:           'Joshua Byrd'
  url:            https://twitter.com/phocks

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/phocks/phocks.github.io
