# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        none

# Setup
title:            phocks
tagline:          'a dev blog or something'
description:      'A weblog by Joshua Byrd.'
url:              https://phocks.github.io
baseurl:          '/'
paginate:         5
timezone:         Australia/Brisbane
encoding:         utf-8

author:
  name:           'Joshua Byrd'
  url:            https://twitter.com/phocks

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/phocks/phocks.github.io

gems:             ['jekyll-paginate']
